### ISSUE TITLE
Documento de abertura do projeto

### ISSUE THREAD

**Issue by kauanpavan** [kauanpavan/Grupo-21-ADS-Salto#10]
- [x] Definir as funcionalidades principais do projeto (Jobbit);
- [x] Descrever o funcionamento do projeto;
- [x] Definir funcionalidades complementares do projeto;

Critério de aceitação: Só será definido como aceito quando a atividade feita for revisada por todos membros do projeto, e no processo de revisão não foram encontrados erros/problemas.

**Comment by PauloFRjr** [comment]
Chegamos na conclusão de quais serão ás funcionalidades principais do projeto e começamos a discutir sobre as funcionalidades complementares, adicionamos os documentos de [abertura ao repositório](https://github.com/kauanpavan/Grupo-21-ADS-Salto/blob/main/Documenta%C3%A7%C3%A3o/Formulario%20de%20cadastro.pdf) e [objetivos do projeto](https://github.com/kauanpavan/Grupo-21-ADS-Salto/blob/main/Documenta%C3%A7%C3%A3o/Objetivo%20do%20projeto.pdf).

**Comment by kauanpavan** [comment]
Estamos movendo a tarefa como concluída, pois na documentação citada acima já temos as informações necessárias para conclusão da mesma e para dar mais foco às atividades pendentes.
