### ISSUE TITLE
Layout do formulário de postagem

### ISSUE THREAD

**Issue by kauanpavan** [kauanpavan/Grupo-21-ADS-Salto#11]
Como usuário, desejo ter um formulário de postagem organizado e fácil de preencher, para que eu possa inserir minhas dúvidas no fórum de maneira rápida e sem complicações.

- [x] Exibir um formulário de postagem claro e bem estruturado.
- [x] Facilitar o preenchimento dos campos com informações identificáveis e labels claras.

Critérios de Aceitação:

- O formulário deve ser visível e acessível na página.
- Todos os campos devem ter labels claramente identificáveis.

**Comment by kauanpavan** [comment]
Segue estruturação do layout baseado em fluxograma:

![Image](https://github.com/user-attachments/assets/9ce9453b-8ad6-4009-a97f-e365ac39f6e1)

**Comment by Tobirago** [comment]
Segue estruturação do layout baseado em wireframe:

![image](https://github.com/user-attachments/assets/ca4c056e-1650-40cf-9055-30196e6933c0)

**Comment by kauanpavan** [comment]
Layout do formulário concluído, segue link:

[Layout do formulário](Documentação/layout_formulário/layout_formulário_final.PNG)

**Comment by davifma** [comment]
A estrutura de decisão do fluxograma de vocês está estranha. Não dá pra fazer o envio e um "SE" ao mesmo tempo.

**Comment by davifma** [comment]
[Layout do formulário](https://github.com/users/kauanpavan/projects/2/views/Documenta%C3%A7%C3%A3o/layout_formul%C3%A1rio/layout_formul%C3%A1rio_final.PNG) não está carregando e não foi atualizado o fluxograma
